### ISSUE TITLE
Telegram is not added as an available medium

### ISSUE THREAD

**Issue by EnessenE** [cmdotcom/text-sdk-javascript#39]
Looking at this code: [Array of channels](https://github.com/cmdotcom/text-sdk-javascript/blob/master/lib/MessageApiClient.ts#L4)

You can notice Telegram is missing while its added to other sdk's.

**Comment by EricSmekens** [comment]
Agreed, labeling this as a good-first-issue for anyone to pick up.

**Comment by EnessenE** [comment]
Fixed in next release
